FROM ubuntu
LABEL maintainer="sevendollar@gmail.com"
WORKDIR /slack
COPY ./*.py /slack/
ENV LANG='C.UTF-8'
ENV SLACK_BOT_TOKEN=''
ENV RUCKUS_USER=''
ENV RUCKUS_PASS=''
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.6 vim curl && \
    ln -s /usr/bin/python3.6 /usr/bin/python && \
    curl -sLO https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm -rf get-pip.py && \
    apt install -y build-essential chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev && \
    curl -sLO https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    tar jxvf phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    mv phantomjs-2.1.1-linux-x86_64/ /usr/local/share/ && \
    ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/ /usr/local/bin/ && \
    ln -s /usr/local/bin/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs && \
    rm -rf phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    pip install slackclient selenium && \
    rm -rf /var/lib/apt/lists/*
CMD ["/usr/bin/python", "/slack/slack_bot.py"]
