FROM golang
LABEL maintainer="sevendollar@gmail.com"
WORKDIR /go
RUN touch /root/.vimrc && \
    echo -e '\nexecute pathogen#infect()\n\
syntax on\n\
filetype plugin indent on\n\
set nocompatible\n\
set backspace=indent,eol,start\n\
set ts=4\n\
set expandtab\n\
imap <F6> <C-x><C-o>' > /root/.vimrc && \
    sed -i '/-e/d' /root/.vimrc && \
    echo 'export GOBIN=$GOPATH/bin' >> /etc/profile && \
    echo 'export GOROOT=$GOPATH' >> /etc/profile && \
    apt update && apt install -y vim && \
    mkdir -p /root/.vim/autoload /root/.vim/bundle && \
    curl -LSso /root/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim && \
    cd /go/src/ && \
    go get github.com/nsf/gocode && \
    cd /go/src/github.com/nsf/gocode && \
    go build && go install && \
    cd /root/.vim/bundle/ && \
    git clone https://github.com/plasticboy/vim-markdown.git && \
    git clone https://github.com/fatih/vim-go.git && \
    git clone https://github.com/Blackrush/vim-gocode.git && \
    rm -rf /var/lib/apt/lists/*
