FROM alpine:latest
LABEL maintainer="sevendollar@gmail.com"
WORKDIR /terraform
RUN apk --update add --no-cache curl unzip git bash && \
    curl -sLo tf https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip?_ga=2.89279580.616740582.1507252388-510355381.1497248072 && \
    unzip tf && \
    mv terraform /usr/local/bin/ && \
    rm tf* && \
    rm -rf /var/lib/apt/lists/* && \
    cp /usr/local/bin/terraform /usr/local/bin/tf && chmod +x /usr/local/bin/tf
CMD ["terraform"]
