#etcd v3.2.7
FROM alpine:latest
LABEL maintainer=sevendollar@gmail.com
RUN apk update && apk add --no-cache curl vim bash tar && \
    curl -sL https://github.com/coreos/etcd/releases/download/v3.2.7/etcd-v3.2.7-linux-amd64.tar.gz | tar zx && \
    cp etcd-v3.2.7-linux-amd64/etcdctl /bin/etcdctl && \
    chmod +x /bin/etcdctl && \
    rm -rf etcd-v3.2.7-linux-amd64
CMD ["etcdctl"]
