FROM alpine:latest
LABEL maintainer="sevendollar@gmail.com"
WORKDIR /packer
RUN apk --update add --no-cache curl unzip git bash && \
    curl -sLo pk https://releases.hashicorp.com/packer/1.1.0/packer_1.1.0_linux_amd64.zip?_ga=2.171572840.933406589.1506588132-299599022.1506588132 && \
    unzip pk && \
    mv packer /usr/local/bin/ && \
    rm pk*
CMD ["packer"]
