FROM alpine:latest
LABEL maintainer="sevendollar@gmail.com"
WORKDIR /terraform
RUN apk --update add --no-cache curl unzip git && \
    curl -sLo tf https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip?_ga=2.154767166.780635085.1506299436-510355381.1497248072 && \
    unzip tf && \
    mv terraform /usr/local/bin/ && \
    rm tf* && \
    rm -rf /var/lib/apt/lists/* && \
    alias tf=terraform
CMD ["terraform"]
