FROM alpine:latest
RUN apk update && apk add --no-cache curl vim bash && \
    curl -s -L -o /bin/cfssl https://pkg.cfssl.org/R1.2/cfssl_linux-amd64 && \
    curl -s -L -o /bin/cfssljson https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64 && \
    chmod +x /bin/cfssl && chmod +x /bin/cfssljson
CMD ["cfssl"]
